T2/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from conta.views import (
    tela_inicial_view,
    registro_view,
    logout_view,
    login_view,
    atualiza_view,
    precisa_autenticar_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', tela_inicial_view, name="tela-inicial"),
    path('postagens/', include('postagens.urls', 'postagens')),
    path('registro/', registro_view, name="tela-registro"),
    path('logout/', logout_view, name="tela-logout"),
    path('login/', login_view, name="tela-login"),
    path('atualiza/', atualiza_view, name="tela-atualiza"),
    path('precisa-autenticar/', precisa_autenticar_view, name="tela-precisa-autenticar"),
    
    #links de redefinição de senha padrão do Django
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
        name="password_change_done"),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"),
        name="password_change"),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
        name="password_reset"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

T2/Blog/postagens/urls.py
from django.urls import path
from postagens.views import (
    cria_post_view,
    detalhes_post_view,
    edita_post_view,
)

app_name= 'postagens'

urlpatterns = [
    path('cria/', cria_post_view, name="cria"),
    path('<slug>/', detalhes_post_view, name="detalhe"),
    path('<slug>/edit/', edita_post_view, name="edita"),
]

T2/Blog/postagens/models.py
from django.db import models

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

def caminho_upload(instance, filename, **kwargs):
    file_path = 'blog/{autor_id}/{titulo}-{filename}'.format(
       autor_id = str(instance.autor.id), titulo=str(instance.titulo), filename=filename
    )
    return file_path

class Postagem(models.Model):
    titulo = models.CharField(max_length=50, null=False, blank=False)
    corpo = models.TextField(max_length=5000, null=False, blank=False)
    imagem = models.ImageField(upload_to=caminho_upload, blank=False)
    data_publicacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Publicação")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #slug cria uma URL automaticamente para as postagens
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.titulo

@receiver(post_delete, sender=Postagem)
def delete_submissao(sender, instance, *args, **kwargs):
    instance.imagem.delete(False)

def pre_salvar_postagem_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.autor.username + "-" + instance.titulo)

pre_save.connect(pre_salvar_postagem_receiver, sender=Postagem)

T2/Blog/postagens/forms.py
from django import forms

from postagens.models import Postagem

class CriaFormularioDaPostagem(forms.ModelForm):

    class Meta:
        model = Postagem
        fields = ['titulo', 'corpo', 'imagem']


class AtualizaFormPostagem(forms.ModelForm):

    class Meta:
        model = Postagem
        fields = ['titulo', 'corpo', 'imagem']

    def save(self, commit=True):
        postagem_blog = self.instance
        postagem_blog.titulo = self.cleaned_data['titulo']
        postagem_blog.corpo = self.cleaned_data['corpo']

        if self.cleaned_data['imagem']:
            postagem_blog.imagem = self.cleaned_data['imagem']

        if commit:
            postagem_blog.save()
        return postagem_blog

T2/Blog/postagens/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse

from postagens.models import Postagem
from postagens.forms import CriaFormularioDaPostagem, AtualizaFormPostagem
from conta.models import Conta

def cria_post_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("tela-precisa-autenticar")
    
    form = CriaFormularioDaPostagem(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        autor = Conta.objects.filter(email=user.email).first()
        obj.autor = autor
        obj.save()
        form = CriaFormularioDaPostagem()

    context['form'] = form

    return render(request, "postagens/cria-post.html", context)

def detalhes_post_view(request, slug):
    context = {}

    postagem_blog = get_object_or_404(Postagem, slug=slug)
    context['postagem_blog'] = postagem_blog

    return render(request, 'postagens/detalhes-post.html', context)

def edita_post_view(request, slug):
    
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("tela-precisa-autenticar")

    postagem_blog = get_object_or_404(Postagem, slug=slug)
    if postagem_blog.autor != user:
        return HttpResponse('Você não é o autor desta postagem.')
    
    if request.POST:
        form = AtualizaFormPostagem(request.POST or None, request.FILES or None, instance=postagem_blog)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Atualizado!"
            postagem_blog = obj

    form = AtualizaFormPostagem(
        initial = {
            "titulo": postagem_blog.titulo,
            "corpo": postagem_blog.corpo,
            "imagem": postagem_blog.imagem,
        }
    )

    context['form'] = form
    return render(request, 'postagens/edita-post.html', context)

T2/Blog/postagens/templates/postagens/snippets/blog-snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>

{% if postagem_blog %}
	<div class="container">
		<div class="row">
			<!-- Postagem do Blog -->
			<div class="card m-auto">
				<a href="{% url 'postagens:detalhe' postagem_blog.slug %}">
					<img class="card-img-top" src="{{postagem_blog.image.url}}">
				</a>
				<div class="card-body mt-2 mb-2">
					<a href="{% url 'postagens:detalhe' postagem_blog.slug %}">
						<h2 class="card-title">{{postagem_blog.titulo}}</h2>
					</a>
					<p class="card-text">{{postagem_blog.corpo|safe|truncatechars:180}}</p>
					{% if postagem_blog.autor == request.user %}
						<a href="{% url 'postagens:edita' postagem_blog.slug %}" class="btn btn-primary">Atualiza</a>
					{% endif %}
				</div>
				<div class="card-footer text-muted">
				Atualizado em {{postagem_blog.data_atualizacao}} por {{postagem_blog.autor}}
				</div>
			</div>
		</div>
	</div>

{% else %}
	<div class="left-column col-lg-7 offset-lg-1">
		<div class="mb-3">
			<div class="card m-auto d-flex flex-column p-3">
				<p class="lead"><b>BEM-VINDX AO DJANGOBLOG!</b></p>
			</div>
		</div>
	</div>

{% endif %}