T2/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from conta.views import (
    tela_inicial_view,
    registro_view,
    logout_view,
    login_view,
    atualiza_view,
    precisa_autenticar_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', tela_inicial_view, name="tela-inicial"),
    path('postagens/', include('postagens.urls', 'postagens')),
    path('registro/', registro_view, name="tela-registro"),
    path('logout/', logout_view, name="tela-logout"),
    path('login/', login_view, name="tela-login"),
    path('atualiza/', atualiza_view, name="tela-atualiza"),
    path('precisa-autenticar/', precisa_autenticar_view, name="tela-precisa-autenticar"),
    
    #links de redefinição de senha padrão do Django
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
        name="password_change_done"),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"),
        name="password_change"),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
        name="password_reset"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

T2/Blog/postagens/urls.py
from django.urls import path
from postagens.views import (
    cria_post_view,
    detalhes_post_view,
    edita_post_view,
)

app_name= 'postagens'

urlpatterns = [
    path('cria/', cria_post_view, name="cria"),
    path('<slug>/', detalhes_post_view, name="detalhe"),
    path('<slug>/edit/', edita_post_view, name="edita"),
]

T2/Blog/conta/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class MeuAdministradorConta(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Usuarios precisam ter um email!")
        if not username:
            raise ValueError("Usuarios precisam ter um username!")

        usuario = self.model(
            email = self.normalize_email(email),
            username = username,
        )

        usuario.set_password(password)
        usuario.save(using=self._db)

        return usuario

    def create_superuser(self, email, username, password):
        usuario = self.create_user(
                email = self.normalize_email(email),
                password = password,
                username = username,
        )
        usuario.is_admin = True
        usuario.is_staff = True
        usuario.is_superuser = True
        usuario.save(using=self._db)
        return usuario


class Conta(AbstractBaseUser):
    email = models.EmailField(verbose_name="Email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='data de entrada', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='ultimo login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active= models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    nome = models.CharField(max_length=50)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MeuAdministradorConta()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_Label):
        return True    

T2/Blog/conta/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from conta.models import Conta

class RegistroForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text="Adicione um email válido")

    class Meta:
        model = Conta
        fields = ("email", "username", "password1", "password2")


class AutenticacaoForm(forms.ModelForm):
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

    class Meta:
        model = Conta
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Login ou Senha Incorreto(a)")


class AtualizaContaForm(forms.ModelForm):
    class Meta:
        model = Conta
        fields = ('email', 'username')

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            #agora, verificaremos se o email existe e se encontra no BD
            try:
                conta = Conta.objects.exclude(pk=self.instance.pk).get(email=email)
            except Conta.DoesNotExist:
                return email
            raise forms.ValidationError("Email %s já está em uso." %email)

    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            #agora, verificaremos se o username existe e se encontra no BD
            try:
                conta = Conta.objects.exclude(pk=self.instance.pk).get(username=username)
            except Conta.DoesNotExist:
                return username
            raise forms.ValidationError("Username %s já está em uso." %username)

T2/Blog/conta/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from operator import attrgetter

from conta.forms import RegistroForm, AutenticacaoForm, AtualizaContaForm
from conta.models import Conta
from postagens.models import Postagem

def tela_inicial_view(request):
    
    context = {}
    postagem_blog = sorted(Postagem.objects.all(), key=attrgetter('data_atualizacao'), reverse=True)
    context['postagem_blog'] = postagem_blog

    return render(request, "conta/home.html", context)

def registro_view(request):
    context = {}
    if request.POST:
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            conta = authenticate(email=email, password=raw_password)
            login(request, conta)
            return redirect('tela-inicial')
        else:
            context['registro_form'] = form
    else:
        #request.GET
        form = RegistroForm()
        context['registro_form'] = form
    
    return render(request, 'conta/registro.html', context)

def logout_view(request):
    logout(request)
    return redirect('tela-inicial')

def login_view(request):
    context = {}

    user = request.user
    #usuário já se encontra logado
    if user.is_authenticated:
        return redirect("tela-inicial")

    #usuário tentou logar (preencheu login e senha) e formulário precisa ser autenticado
    if request.POST:
        form = AutenticacaoForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect("tela-inicial")
    else: #usuário não tentou logar e se encontra na página de login
        form = AutenticacaoForm()

    context['login_form'] = form
    return render(request, 'conta/login.html', context)

def atualiza_view(request):
    if not request.user.is_authenticated:
        return redirect("tela-login")

    context = {}

    if request.POST:
        form = AtualizaContaForm(request.POST, instance=request.user)
        if form.is_valid():
            form.initial = {
                "email": request.POST['email'],
                "username": request.POST['username'],
            }
            form.save()
            context['msg_sucesso'] = "Alteração salva!"
    else:
        form = AtualizaContaForm(
            initial = {
                "email": request.user.email,
                "username": request.user.username,
            }
        )
    context['conta_form'] = form

    postagens_blog = Postagem.objects.filter(autor=request.user)
    context['postagens_blog'] = postagens_blog

    return render(request, 'conta/atualiza.html', context)

def precisa_autenticar_view(request):
    return render(request, 'conta/precisa-autenticar.html', {})

T2/Blog/conta/templates/conta/atualiza.html
{% extends 'base.html' %}

{% block content %}

    <style type="text/css">
        .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
        }

        .form-signin .form-floating:focus-within {
        z-index: 2;
        }

        .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        }

        .form-signin input[type="text"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        }

        .h3{
            text-align: center;
        }

        .postagens_blog{
            max-width: 500px;
            width: 100%;
            margin: auto;
        }

    </style>

    <form class="form-signin w-100 m-auto" method="post">{% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Dados da Conta</h1>

        <div class="form-floating">
            <input  type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" value={{conta_form.initial.email}}>
            <label for="floatingInput">Email</label>
        </div>

        <div class="form-floating">
            <input type="text" name="username" class="form-control" id="floatingUsername" placeholder="Username" value={{conta_form.initial.username}}>
            <label for="floatingInput">Username</label>
        </div>

        {% for field in conta_form %}
            <p>
                <!--trata erros de formulário (ex: não preencheu campo do login, número mínimo de caracteres da senha não foi escrito)-->
                {% for error in field.errors %}
                    <p style="color: red;">{{error}}</p>
                {% endfor %}
            </p>
        {% endfor %}

        <!--trata erros no preenchimento dos formulários (ex: senha errada, login inválido)-->
        {% if conta_form.non_field_errors %}
            <div style="color: red;">
                <p>{{conta_form.non_field_errors}}</p>
            </div>
        {% endif %}

        {% if msg_sucesso %}
            <p style="color: green; text-align:center;">{{msg_sucesso}}</p>
        {% endif %}

        <button class="w-100 btn btn-lg btn-primary" type="submit">Salvar alterações</button>
    </form>

    <div class="d-flex flex-column">
        <a class="m-auto" href="{% url 'password_change' %}">Trocar Senha</a>
    </div>

    <div class="container mt-4 p-4">
        <div class="row">
            <div class="postagens_blog">
                <h3 class="mb-3 font-weight-normal">Postagens do Blog:</h3>
                {% if postagens_blog %}
                    <ul>
                        {% for post in postagens_blog %}
                            <a href="{% url 'postagens:detalhe' post.slug %}" style="text-decoration: none;">
                                <li class="list-group-item">{{post}}</li>
                            </a>
                        {% endfor %}
                    </ul>
                {% else %}
                <p>Você não tem postagens ainda! Faça sua primeira postagem <a href="{% url 'postagens:cria' %}">aqui</a>!</p>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock content %}

T2/Blog/conta/templates/conta/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- conteúdo main -->
<div class="container">
	<div class="row">

		<!-- feed do Blog -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- 'criar postagem' -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'django-logo.png' %}" width="72" height="72">
					<p class="lead">Este site é o equivalente ao Blogspot, só que piorado. É um Blog feito em Django.
                        Realiza CRUD de usuários e CRUD de postagens... Aproveite!</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'postagens:cria' %}">Criar Postagem</a></p>
				</div>
			</div>
			<!-- end 'criar postagem' -->

			<!-- Postagens do Blog -->
			{% if postagem_blog %}
				{% for postagem in postagem_blog %}
					<div class="blog-post-container">
						{% include 'postagens/snippets/blog-snippet.html' with postagem_blog=postagem %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'postagens/snippets/blog-snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Postagens do Blog-->

		</div>
		<!-- end blog feed -->


		<!-- 'criar postagem' coluna direita -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'django-logo.png' %}" width="72" height="72">
				<p class="lead">Este site é o equivalente ao Blogspot, só que piorado. É um Blog feito em Django.
                    Realiza CRUD de usuários e CRUD de postagens... Aproveite!</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'postagens:cria' %}">Criar Postagem</a></p>
			</div>
		
		</div>
		<!-- end 'criar postagem' coluna direita -->



	</div>
</div>

{% endblock content %}

T2/Blog/conta/templates/conta/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <style type="text/css">
        .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
        }

        .form-signin .form-floating:focus-within {
        z-index: 2;
        }

        .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        }

        .h3{
            text-align: center;
        }

    </style>

    <form class="form-signin w-100 m-auto" method="post">{% csrf_token %}
        <div class="d-flex flex-column pb-3">
            <img class="img-fluid mx-auto d-block" src="{% static 'django-logo.png' %}" alt="RD logo" width="100" height="100">
        </div>
        <h1 class="h3 mb-3 fw-normal">Login</h1>

        <div class="form-floating">
            <input  type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email</label>
        </div>

        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingInput">Senha</label>
        </div>

        {% for field in login_form %}
            <p>
                <!--trata erros de formulário (ex: não preencheu campo do login, número mínimo de caracteres da senha não foi escrito)-->
                {% for error in field.errors %}
                    <p style="color: red;">{{error}}</p>
                {% endfor %}
            </p>
        {% endfor %}

        <!--trata erros no preenchimento dos formulários (ex: senha errada, login inválido)-->
        {% if login_form.non_field_errors %}
            <div style="color: red;">
                <p>{{login_form.non_field_errors}}</p>
            </div>
        {% endif %}

        <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
    </form>

    <div class="d-flex flex-column">
        <a class="m-auto" href="{% url 'password_reset' %}">Redefinir Senha</a>
    </div>

{% endblock content %}

T2/Blog/conta/templates/conta/precisa-autenticar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="d-flex flex-column">
        <p class="m-auto">Você precisa logar para ver esta página</p>
        <p class="m-auto">
            <a href="{% url 'tela-registro' %}">Crie uma Conta</a> ou
            <a href="{% url 'tela-login' %}">Entre</a>
        </p>
    </div>
</div>

{% endblock content %}

T2/Blog/conta/templates/conta/registro.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <style type="text/css">
        .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
        }

        .form-signin .form-floating:focus-within {
        z-index: 2;
        }

        .form-signin input[type="email"] {
        margin-bottom: 10px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        }

        .form-signin input[type="text"] {
        margin-bottom: 10px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        }

        input::placeholder {
        color: red;
        }

        .h3{
            text-align: center;
        }

    </style>

    <form class="form-signin w-100 m-auto" method="post">{% csrf_token %}
        <div class="d-flex flex-column pb-3">
            <img class="img-fluid mx-auto d-block" src="{% static 'django-logo.png' %}" alt="RD logo" width="100" height="100">
        </div>
        
        <h1 class="h3 mb-3 fw-normal">Criar uma Conta</h1>

        <div class="form-floating">
            <input  type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email</label>
        </div>

        <div class="form-floating">
            <input type="text" name="username" class="form-control" id="floatingUsername" placeholder="Username">
            <label for="floatingInput">Username</label>
        </div>

        <div class="form-floating">
            <input type="password" name="password1" class="form-control" id="floatingPassword1" placeholder="Senha">
            <label for="floatingInput">Senha</label>
        </div>

        <div class="form-floating">
            <input type="password" name="password2" class="form-control" id="floatingPassword2" placeholder="Confirmar Senha">
            <label for="floatingInput">Confirmar Senha</label>
        </div>

        {% for field in registro_form %}
            <p>
                <!--trata erros de formulário (ex: não preencheu campo do login, número mínimo de caracteres da senha não foi escrito)-->
                {% for error in field.errors %}
                    <p style="color: red;">{{error}}</p>
                {% endfor %}
            </p>
        {% endfor %}

        <!--trata erros no preenchimento dos formulários (ex: senha errada, login inválido)-->
        {% if registro_form.non_field_errors %}
            <div style="color: red;">
                <p>{{registro_form.non_field_errors}}</p>
            </div>
        {% endif %}

        <button class="w-100 btn btn-lg btn-primary" type="submit">Criar Conta!</button>
    </form>

{% endblock content %}